### ISSUE TITLE
jmuxer with h264 and opus

### ISSUE THREAD

**Issue by frankville** [samirkumardas/jmuxer#25]
Hi Samir, first I want to congratulate you for developing this tool. It's awesome. The reason of this issue is to ask you if it is possible to adapt jmuxer so it can receive opus audio instead of AAC. I think this feature would have an incredible utility because we will be able to send the mediaStream from the video element straight through WebRTC which doesn't support AAC right now.

**Comment by samirkumardas** [comment]
Thank you.

Problem is MP4 container does not support opus codec.  Also you can not run raw opus data on the browser directly like AAC for example using html audio tag.  
Browser support opus internally when you use webRTC but it does not provide any API to run opus without webRTC. At least I don't know about it.

So only solution is converting opus to PCM data and finally play through using javascript Audio API. I have another project that convert opus to PCM https://github.com/samirkumardas/opus-to-pcm

You can play h264 with jmuxer and run opus data separately but main challenge would be syncing of audio/video :(   Also Javascript Audio API is still on its infancy stage and it create unwanted noise randomly during play.  I had to gone through this terrible situation.

Anyways, since you are using webRTC why do you need this project?

**Comment by frankville** [comment]
Hi Samir, here is a sample of ISO-BMFF with opus from chrome [https://googlechrome.github.io/samples/media/opus-in-mp4-for-mse.html](url) . I saw this a couple of days ago and since I want to be able to use media elements with WebRTC I thought it could be really awsome to have it in jmuxer. I am using/testing jmuxer on a node-webkit app (client side app, that's why I'm not using something like janus) where I get h264 frames from other sources like rtmp and so far it's working really well but I can only play audio if I use your other tool -pcm-player- but the sound quality of pcm is definitely not good. Besides I can't send that audio stream to WebRTC. It would be really cool if jmuxer could play opus. The quality of sound is really good. There are many who are looking to stream non-webrtc sources properly into webrtc-based apps. As far as I know there is no such tool or if there is they are next to imposible to make them work.

**Comment by samirkumardas** [comment]
Oops! I admit I am now backdated with MSE! Sorry I have not looked recent changes.
Yes, I see opus is supported by browser at least latest chrome and FF.
Will try to cope opus when get some time but not sure when would be able to work on. Have to do study. 
by the way, if you get any resource Or able to do it,  please don't forget to share.

**Comment by frankville** [comment]
Great! The media capabilities on the web are evolving fastly. I'll try to help with code or testing also.
