### ISSUE TITLE
Issues with live playback in Safari

### ISSUE THREAD

**Issue by FD-** [samirkumardas/jmuxer#68]
Hi,
I'm trying to use [pi-h264-to-browser](https://github.com/dans98/pi-h264-to-browser), which basically transmits live raw h264 through a websocket, which is then rendered in the browser with jmuxer.

While this works fine in Chrome (on macOS), I cannot seem to get it properly working in Safari (on macOS or iOS). 
The stream plays for a very short time, when it stops and can only be made to resume by manually clicking the play button in the video controls. Still, it seems as soon as playback has caught up with the frames that were received while playback was paused, it stops again.

Since the problem seems to be linked with jmuxer, I was hoping you have an idea what might be the problem and how it can be solved. The specific parameterisation used is
```
var jmuxer = new JMuxer({
    node: 'stream',
    mode: 'video',
    flushingTime: 0,
    fps: $fps,
    debug: false
});
```

I tried enabling debug logging, but the produced messages don't seem to indicate any error in the browser's console.

Is this a known problem of the jmuxer library? Is there any workaround?

Any help is highly appreciated!

**Comment by samirkumardas** [comment]
what is your safari version, v14.x?
Can you try demo  https://samirkumardas.github.io/jmuxer/ if it works in your safari?  Let me know how it goes.

**Comment by FD-** [comment]
Thanks for your response! 

I'm using Safari Version 14.0 (15610.1.28.1.9, 15610). I can confirm that the demo works fine in my browser. Is there anything it does different than the approach I described above? Well, I assume it's not streaming live h264, right?

**Comment by samirkumardas** [comment]
> Well, I assume it's not streaming live h264, right?
It is not live streaming but it is similar to streaming. You can check the server demo code. [https://github.com/samirkumardas/jmuxer/blob/master/example/server.js](url)

However, this issue happens to Safari. I also faced this issue earlier. It happens when the safari gets little buffer and it is running out of the buffer to play.  You can try adjusting `flushingTime` to a larger value e.g. 500 to 2000 that will cause a latency but it may help.

If that works, you can adjust  `flushingTime` for the safari only when you instantiate jmuxer

**Comment by samirkumardas** [comment]
another approach could be caching some initial buffer before initiating Jmuxer so Safari always gets some ready buffer in advance.  Though I have not tested it myself.
