### ISSUE TITLE
When H264 decode error happen,it can't continue to decode and show video later 

### ISSUE THREAD

**Issue by waiter89** [samirkumardas/jmuxer#9]
[index.html.txt](https://github.com/samirkumardas/jmuxer/files/2064617/index.html.txt)

**Comment by samirkumardas** [comment]
You have not provide any time information. You can provide chunk duration during `feed` OR you can use a fixed frame rate and fps can be defined when you instantiate the jmuxer.

```
function parse(data) {
		var input = new Uint8Array(data),
			dv = new DataView(input.buffer),
			video;
		video = input.subarray(16);

		return {
		  video: video
                duration: ??? -----> missing
		};
	}
```

There is no duration present in your feed data. If you don't know your chunk duration and have a fixed frame rate then you can set during instantiate. 

```
jmuxer = new JMuxer({
			 node: 'player',
			 flushingTime:150,
			 mode:'video',
                         fps: 24  -------> you can set  fps  here
		  });

```

I am closing your other issue since it is duplicate

**Comment by samirkumardas** [comment]
Duplicate https://github.com/samirkumardas/jmuxer/issues/9
